title: Eleventy Sveltia CMS Starter
description: A template for building a fast Eleventy blog with Sveltia CMS, with deployment to Netlify
url: https://eleventy-sveltia-cms-starter.netlify.app
theme:
  colors:
    primary: "#2e51ed"
    secondary: "white"
    background: "#f1f1f1"
    text: "#111111"
    accent: "#e91e63"
  fonts:
    base: "system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,Cantarell,Noto Sans,sans-serif"
    heading: "inherit"
  spacing:
    - "0.25rem"
    - "0.5rem"
    - "1rem"
    - "1.5rem"
    - "2rem"
  logo: "/assets/img/logo.svg"
  logoAlt: "Site logo"
  customCSS: ""
